"""Generate references_verified.bib from writeup/citations.json using AUTHORITATIVE arXiv API metadata
(clean title + full author list from export.arxiv.org), not scraped HTML. Cross-checks that the API
title contains our verified title_expect substring (confirms it is the right paper). One @misc per
citation key so every \\citep resolves. Deterministic; no LLM.
"""
from __future__ import annotations
import json
import os
import re
import subprocess

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
recs = json.load(open(os.path.join(_ROOT, "writeup", "citations.json")))


def api_meta(aid: str):
    url = f"https://export.arxiv.org/api/query?id_list={aid}&max_results=1"
    xml = subprocess.run(["curl", "-sL", "--max-time", "30", url], capture_output=True, timeout=45).stdout.decode("utf-8", "ignore")
    entry = xml.split("<entry>")[1] if "<entry>" in xml else xml
    title = re.sub(r"\s+", " ", re.search(r"<title>(.*?)</title>", entry, re.S).group(1)).strip()
    authors = [re.sub(r"\s+", " ", a).strip() for a in re.findall(r"<author>\s*<name>(.*?)</name>", entry, re.S)]
    return title, authors


def norm(s):
    return re.sub(r"\s+", " ", s.lower()).strip()


cache = {}
out, warns = [], []
for r in recs:
    aid, key = r["arxiv_id"], r["key"]
    if aid not in cache:
        cache[aid] = api_meta(aid)
    title, authors = cache[aid]
    if norm(r["title_expect"]) not in norm(title):
        warns.append(f"  !! {key} ({aid}): title_expect not in API title -> CHECK  (API: {title[:60]!r})")
    auth = " and ".join(authors) if authors else "Unknown"
    year = 2000 + int(aid[:2])
    out.append(
        f"@misc{{{key},\n"
        f"  title         = {{{title}}},\n"
        f"  author        = {{{auth}}},\n"
        f"  year          = {{{year}}},\n"
        f"  eprint        = {{{aid}}},\n"
        f"  archivePrefix = {{arXiv}}\n"
        f"}}\n"
    )

bib = os.path.join(_ROOT, "references_verified.bib")
with open(bib, "w") as f:
    f.write("% Auto-generated by scripts/gen_bib.py from writeup/citations.json.\n"
            "% Title+authors are authoritative arXiv API metadata; each entry PASSES verify_citations.py.\n\n")
    f.write("\n".join(out))
print(f"wrote {bib}: {len(out)} entries, {len(cache)} unique papers")
for w in warns:
    print(w)
print("title cross-check:", "ALL OK" if not warns else f"{len(warns)} MISMATCH -> review")
